# (PART\*) Primera sección

# Introducción

El palíndromo altamente iterado 1 (HIP1 por sus siglas en inglés) cuya secuencia es 5'-GCGATCGC-3’, está ampliamente representado en las cianobacterias con excepción de las pico-cianobacterias marinas y otros linajes. El origen de HIP1 y su función (si es que tiene alguna) permanecen desconocidos. Se ha observado que el sitio de reconocimiento (5'-Gm6ATC-3 ') de la enzima Dam metiltransferasa específica para adenina N6 de clase D12 (Dam-met) y el sitio de reconocimiento de DmtC (5'-m5CGATCG-3 ') están contenidos en HIP1, lo que sugiere una posible relación. Sin embargo, la asociación funcional de otros genes con HIP1 no se ha reportado. Informamos de un conjunto de genes cuyo patrón de presencia/ausencia está asociado con la abundancia de HIP1, lo que sugiere una relación funcional. También informamos de la presencia y representación excesiva de otros palíndromos altamente iterados (HIP) en linajes que carecen de HIP1. Para ello, utilizamos 127 genomas de cianobacterias que se clasificaron en dos grupos según la sobrerrepresentación de HIP1. Luego, nos preguntamos si hay familias génicas cuyo patrón de presencia/ausencia coincidiera con la clasificación de los genomas (con respecto a la sobrerrepresentación de HIP1). Ya que ninguna familia génica coincidió perfectamente, buscamos aquellas con al menos 80% de coicidencia. 20 de 89 familias génicas identificadas, están asociadas con procesos que implican modificación y/o unión al ADN. Por ejemplo, aquellas con dominios que conforman transportadores ABC, de los que se ha sugerido una función como traslocadores de ADN en B. subtillis. También encontramos familias génicas que podrían participar en mecanismos anteriormente propuestos para aumentar la abundancia de HIP1. Por ejemplo, el mecanismo hipotético sugerido por Elhai J. (2015) en el cual participa el sistema de reparación dirigido por metilación (MMR). En relación con este último mecanismo identificamos un posible análogo de la proteína mutH específico para sitios metilados GmC y algunas enzimas con función de endonucleasa. Por ejemplo, algunas inteínas con dominio de endonucleasa como aquel que está presente en la ADN pol III sub unidad alfa, o como las proteínas con dominio GIY-GIY endonucleasa. El conjunto de familias génicas reportado en este trabajo podría servir para realizar experimentos posteriores para esclarecer la importancia de estas enzimas en el origen y evolución de HIP1.